CREATE TABLE companies (
    company_id INTEGER PRIMARY KEY,
    company_name TEXT,
    sector TEXT
);

CREATE TABLE profitandloss (
    id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE balancesheet (
    id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE cashflow (
    id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE analysis (
    id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE documents (
    id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE prosandcons (
    id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE sectors (
    id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE financial_ratios (
    id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE peer_groups (
    id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE stock_prices (
    id INTEGER PRIMARY KEY AUTOINCREMENT
);